### ISSUE TITLE
Use `return` not `raise` in Option.validate

### ISSUE THREAD

**Issue by pddg** [pddg/uroboros#39]
If the validate function is not overwritten, it rases following exception.
```sh
Traceback (most recent call last):
  File "examples/main.py", line 310, in <module>
    exit_code = root_cmd.execute()
  File "/home/pudding/.local/share/virtualenvs/hoger-EWaBsfe_/lib/python3.7/site-packages/uroboros/command.py", line 67, in execute
    exceptions = self._validate_all(args, commands)
  File "/home/pudding/.local/share/virtualenvs/hoge-EWaBsfe_/lib/python3.7/site-packages/uroboros/command.py", line 281, in _validate_all
    exceptions.extend(cmd.validate(args))
  File "/home/pudding/.local/share/virtualenvs/hoge-EWaBsfe_/lib/python3.7/site-packages/uroboros/command.py", line 292, in validate
    exceptions.extend(opt.validate(args))
  File "/home/pudding/.local/share/virtualenvs/hoge-EWaBsfe_/lib/python3.7/site-packages/uroboros/option.py", line 30, in validate
    raise []
TypeError: exceptions must derive from BaseException
```

**Comment by pddg** [comment]
https://github.com/pddg/uroboros/blob/v0.2.2/uroboros/option.py#L28
